name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for accurate branch/tag detection
      - name: Determine environment
        id: env
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "environment=preview" >> $GITHUB_OUTPUT
            echo "deploy_branch=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "deploy_branch=main" >> $GITHUB_OUTPUT
          fi
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Automatically deploy to the github-pages branch
          branch: ${{ steps.env.outputs.deploy_branch }}
          # Automatically skip the creation of a CNAME file
          enable_jekyll: false
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: steps.env.outputs.environment == 'production'
      - name: Deploy to GitHub Pages Preview
        id: deployment
        uses: actions/deploy-pages@v4
        if: steps.env.outputs.environment == 'preview'
        with:
          # The GitHub Pages deployment branch
          branch: ${{ steps.env.outputs.deploy_branch }}
      - name: Add pull request comment
        if: steps.env.outputs.environment == 'preview'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Preview Deployment"
          message: |
            A preview deployment of this pull request is available at:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.pull_request.number }}
